fn main() {
    windows::build!(
        windows::ai::machine_learning::*
        windows::ai::machine_learning::preview::*
        windows::application_model::*
        windows::application_model::activation::*
        windows::application_model::app_extensions::*
        windows::application_model::app_service::*
        windows::application_model::appointments::*
        windows::application_model::appointments::appointments_provider::*
        windows::application_model::appointments::data_provider::*
        windows::application_model::background::*
        windows::application_model::calls::*
        windows::application_model::calls::background::*
        windows::application_model::calls::provider::*
        windows::application_model::chat::*
        windows::application_model::communication_blocking::*
        windows::application_model::contacts::*
        windows::application_model::contacts::data_provider::*
        windows::application_model::contacts::provider::*
        windows::application_model::conversational_agent::*
        windows::application_model::core::*
        windows::application_model::data_transfer::*
        windows::application_model::data_transfer::drag_drop::*
        windows::application_model::data_transfer::drag_drop::core::*
        windows::application_model::data_transfer::share_target::*
        windows::application_model::email::*
        windows::application_model::email::data_provider::*
        windows::application_model::extended_execution::*
        windows::application_model::extended_execution::foreground::*
        windows::application_model::lock_screen::*
        windows::application_model::payments::*
        windows::application_model::payments::provider::*
        windows::application_model::preview::holographic::*
        windows::application_model::preview::ink_workspace::*
        windows::application_model::preview::notes::*
        windows::application_model::resources::*
        windows::application_model::resources::core::*
        windows::application_model::resources::management::*
        windows::application_model::search::*
        windows::application_model::search::core::*
        windows::application_model::social_info::*
        windows::application_model::social_info::provider::*
        windows::application_model::store::*
        windows::application_model::store::license_management::*
        windows::application_model::store::preview::*
        windows::application_model::store::preview::install_control::*
        windows::application_model::user_activities::*
        windows::application_model::user_activities::core::*
        windows::application_model::user_data_accounts::*
        windows::application_model::user_data_accounts::provider::*
        windows::application_model::user_data_accounts::system_access::*
        windows::application_model::user_data_tasks::*
        windows::application_model::user_data_tasks::data_provider::*
        windows::application_model::voice_commands::*
        windows::application_model::wallet::*
        windows::application_model::wallet::system::*
        windows::data::html::*
        windows::data::json::*
        windows::data::pdf::*
        windows::data::text::*
        windows::data::xml::dom::*
        windows::data::xml::xsl::*
        windows::devices::*
        windows::devices::adc::*
        windows::devices::adc::provider::*
        windows::devices::all_joyn::*
        windows::devices::background::*
        windows::devices::bluetooth::*
        windows::devices::bluetooth::advertisement::*
        windows::devices::bluetooth::background::*
        windows::devices::bluetooth::generic_attribute_profile::*
        windows::devices::bluetooth::rfcomm::*
        windows::devices::custom::*
        windows::devices::display::*
        windows::devices::display::core::*
        windows::devices::enumeration::*
        windows::devices::enumeration::pnp::*
        windows::devices::geolocation::*
        windows::devices::geolocation::geofencing::*
        windows::devices::gpio::*
        windows::devices::gpio::provider::*
        windows::devices::haptics::*
        windows::devices::human_interface_device::*
        windows::devices::i2c::*
        windows::devices::i2c::provider::*
        windows::devices::input::*
        windows::devices::input::preview::*
        windows::devices::lights::*
        windows::devices::lights::effects::*
        windows::devices::midi::*
        windows::devices::perception::*
        windows::devices::perception::provider::*
        windows::devices::point_of_service::*
        windows::devices::point_of_service::provider::*
        windows::devices::portable::*
        windows::devices::power::*
        windows::devices::printers::*
        windows::devices::printers::extensions::*
        windows::devices::pwm::*
        windows::devices::pwm::provider::*
        windows::devices::radios::*
        windows::devices::scanners::*
        windows::devices::sensors::*
        windows::devices::sensors::custom::*
        windows::devices::serial_communication::*
        windows::devices::smart_cards::*
        windows::devices::sms::*
        windows::devices::spi::*
        windows::devices::spi::provider::*
        windows::devices::usb::*
        windows::devices::wi_fi::*
        windows::devices::wi_fi_direct::*
        windows::devices::wi_fi_direct::services::*
        windows::embedded::device_lockdown::*
        windows::foundation::*
        windows::foundation::collections::*
        windows::foundation::diagnostics::*
        windows::foundation::metadata::*
        windows::foundation::numerics::*
        windows::gaming::input::*
        windows::gaming::input::custom::*
        windows::gaming::input::force_feedback::*
        windows::gaming::input::preview::*
        windows::gaming::preview::*
        windows::gaming::preview::games_enumeration::*
        windows::gaming::ui::*
        windows::gaming::xbox_live::*
        windows::gaming::xbox_live::storage::*
        windows::globalization::*
        windows::globalization::collation::*
        windows::globalization::date_time_formatting::*
        windows::globalization::fonts::*
        windows::globalization::number_formatting::*
        windows::globalization::phone_number_formatting::*
        windows::graphics::*
        windows::graphics::capture::*
        windows::graphics::directx::*
        windows::graphics::directx::direct3d11::*
        windows::graphics::display::*
        windows::graphics::display::core::*
        windows::graphics::effects::*
        windows::graphics::holographic::*
        windows::graphics::imaging::*
        windows::graphics::printing::*
        windows::graphics::printing::option_details::*
        windows::graphics::printing::print_ticket::*
        windows::graphics::printing::workflow::*
        windows::graphics::printing3d::*
        windows::management::*
        windows::management::core::*
        windows::management::deployment::*
        windows::management::deployment::preview::*
        windows::management::policies::*
        windows::management::update::*
        windows::management::workplace::*
        windows::media::*
        windows::media::app_broadcasting::*
        windows::media::app_recording::*
        windows::media::audio::*
        windows::media::capture::*
        windows::media::capture::core::*
        windows::media::capture::frames::*
        windows::media::casting::*
        windows::media::closed_captioning::*
        windows::media::content_restrictions::*
        windows::media::control::*
        windows::media::core::*
        windows::media::core::preview::*
        windows::media::devices::*
        windows::media::devices::core::*
        windows::media::dial_protocol::*
        windows::media::editing::*
        windows::media::effects::*
        windows::media::face_analysis::*
        windows::media::import::*
        windows::media::media_properties::*
        windows::media::miracast::*
        windows::media::ocr::*
        windows::media::play_to::*
        windows::media::playback::*
        windows::media::playlists::*
        windows::media::protection::*
        windows::media::protection::play_ready::*
        windows::media::render::*
        windows::media::speech_recognition::*
        windows::media::speech_synthesis::*
        windows::media::streaming::adaptive::*
        windows::media::transcoding::*
        windows::networking::*
        windows::networking::background_transfer::*
        windows::networking::connectivity::*
        windows::networking::network_operators::*
        windows::networking::proximity::*
        windows::networking::push_notifications::*
        windows::networking::service_discovery::dnssd::*
        windows::networking::sockets::*
        windows::networking::vpn::*
        windows::networking::xbox_live::*
        windows::perception::*
        windows::perception::automation::core::*
        windows::perception::people::*
        windows::perception::spatial::*
        windows::perception::spatial::preview::*
        windows::perception::spatial::surfaces::*
        windows::phone::*
        windows::phone::application_model::*
        windows::phone::devices::notification::*
        windows::phone::devices::power::*
        windows::phone::management::deployment::*
        windows::phone::media::devices::*
        windows::phone::notification::management::*
        windows::phone::personal_information::*
        windows::phone::personal_information::provisioning::*
        windows::phone::speech::recognition::*
        windows::phone::system::*
        windows::phone::system::power::*
        windows::phone::system::profile::*
        windows::phone::system::user_profile::game_services::core::*
        windows::phone::ui::input::*
        windows::security::authentication::identity::*
        windows::security::authentication::identity::core::*
        windows::security::authentication::identity::provider::*
        windows::security::authentication::online_id::*
        windows::security::authentication::web::*
        windows::security::authentication::web::core::*
        windows::security::authentication::web::provider::*
        windows::security::authorization::app_capability_access::*
        windows::security::credentials::*
        windows::security::credentials::ui::*
        windows::security::cryptography::*
        windows::security::cryptography::certificates::*
        windows::security::cryptography::core::*
        windows::security::cryptography::data_protection::*
        windows::security::data_protection::*
        windows::security::enterprise_data::*
        windows::security::exchange_active_sync_provisioning::*
        windows::security::isolation::*
        windows::services::cortana::*
        windows::services::maps::*
        windows::services::maps::guidance::*
        windows::services::maps::local_search::*
        windows::services::maps::offline_maps::*
        windows::services::store::*
        windows::services::targeted_content::*
        windows::storage::*
        windows::storage::access_cache::*
        windows::storage::bulk_access::*
        windows::storage::compression::*
        windows::storage::file_properties::*
        windows::storage::pickers::*
        windows::storage::pickers::provider::*
        windows::storage::provider::*
        windows::storage::search::*
        windows::storage::streams::*
        windows::system::*
        windows::system::diagnostics::*
        windows::system::diagnostics::device_portal::*
        windows::system::diagnostics::telemetry::*
        windows::system::diagnostics::trace_reporting::*
        windows::system::display::*
        windows::system::inventory::*
        windows::system::power::*
        windows::system::power::diagnostics::*
        windows::system::preview::*
        windows::system::profile::*
        windows::system::profile::system_manufacturers::*
        windows::system::remote_desktop::*
        windows::system::remote_systems::*
        windows::system::threading::*
        windows::system::threading::core::*
        windows::system::update::*
        windows::system::user_profile::*
        windows::ui::*
        windows::ui::accessibility::*
        windows::ui::application_settings::*
        windows::ui::composition::*
        windows::ui::composition::core::*
        windows::ui::composition::desktop::*
        windows::ui::composition::diagnostics::*
        windows::ui::composition::effects::*
        windows::ui::composition::interactions::*
        windows::ui::composition::scenes::*
        windows::ui::core::*
        windows::ui::core::animation_metrics::*
        windows::ui::core::preview::*
        windows::ui::input::*
        windows::ui::input::core::*
        windows::ui::input::inking::*
        windows::ui::input::inking::analysis::*
        windows::ui::input::inking::core::*
        windows::ui::input::inking::preview::*
        windows::ui::input::preview::*
        windows::ui::input::preview::injection::*
        windows::ui::input::spatial::*
        windows::ui::notifications::*
        windows::ui::notifications::management::*
        windows::ui::popups::*
        windows::ui::shell::*
        windows::ui::start_screen::*
        windows::ui::text::*
        windows::ui::text::core::*
        windows::ui::view_management::*
        windows::ui::view_management::core::*
        windows::ui::web_ui::*
        windows::ui::web_ui::core::*
        windows::ui::window_management::*
        windows::ui::window_management::preview::*
        windows::ui::xaml::*
        windows::ui::xaml::automation::*
        windows::ui::xaml::automation::peers::*
        windows::ui::xaml::automation::provider::*
        windows::ui::xaml::automation::text::*
        windows::ui::xaml::controls::*
        windows::ui::xaml::controls::maps::*
        windows::ui::xaml::controls::primitives::*
        windows::ui::xaml::core::direct::*
        windows::ui::xaml::data::*
        windows::ui::xaml::documents::*
        windows::ui::xaml::hosting::*
        windows::ui::xaml::input::*
        windows::ui::xaml::interop::*
        windows::ui::xaml::markup::*
        windows::ui::xaml::media::*
        windows::ui::xaml::media::animation::*
        windows::ui::xaml::media::imaging::*
        windows::ui::xaml::media::media3d::*
        windows::ui::xaml::navigation::*
        windows::ui::xaml::printing::*
        windows::ui::xaml::resources::*
        windows::ui::xaml::shapes::*
        windows::web::*
        windows::web::atom_pub::*
        windows::web::http::*
        windows::web::http::diagnostics::*
        windows::web::http::filters::*
        windows::web::http::headers::*
        windows::web::syndication::*
        windows::web::ui::*
        windows::web::ui::interop::*
        windows::win32::active_directory::*
        windows::win32::all_joyn::*
        windows::win32::antimalware::*
        windows::win32::application_installation_and_servicing::*
        windows::win32::appx_packaging::*
        windows::win32::audio::*
        windows::win32::automation::*
        windows::win32::background_intelligent_transfer_service::*
        windows::win32::bluetooth::*
        windows::win32::cloud_filters::*
        windows::win32::com::*
        windows::win32::component_services::*
        windows::win32::compression::*
        windows::win32::controls::*
        windows::win32::core_audio::*
        windows::win32::data_deduplication::*
        windows::win32::data_exchange::*
        windows::win32::debug::*
        windows::win32::developer_licensing::*
        windows::win32::device_access::*
        windows::win32::device_and_driver_installation::*
        windows::win32::dhcp::*
        windows::win32::direct2d::*
        windows::win32::direct3d10::*
        windows::win32::direct3d11::*
        windows::win32::direct3d12::*
        windows::win32::direct3d9::*
        windows::win32::direct3d_hlsl::*
        windows::win32::direct_composition::*
        windows::win32::direct_draw::*
        windows::win32::direct_ml::*
        windows::win32::direct_manipulation::*
        windows::win32::direct_show::*
        windows::win32::direct_write::*
        windows::win32::display_devices::*
        windows::win32::distributed_file_system::*
        windows::win32::dns::*
        windows::win32::dwm::*
        windows::win32::dxgi::*
        windows::win32::enhanced_storage::*
        windows::win32::etw::*
        windows::win32::extensible_authentication_protocol::*
        windows::win32::fax::*
        windows::win32::file_sever_resource_manager::*
        windows::win32::file_system::*
        windows::win32::game_mode::*
        windows::win32::gaming_device_info::*
        windows::win32::gdi::*
        windows::win32::group_policy_management_console::*
        windows::win32::hardware_counter_profiling::*
        windows::win32::hi_dpi::*
        windows::win32::hid::*
        windows::win32::html_help::*
        windows::win32::http::*
        windows::win32::imapi::*
        windows::win32::iscsi_disc::*
        windows::win32::index_server::*
        windows::win32::ink_input::*
        windows::win32::installable_file_systems::*
        windows::win32::interaction_context::*
        windows::win32::intl::*
        windows::win32::ip_helper::*
        windows::win32::ipc::*
        windows::win32::js::*
        windows::win32::kernel::*
        windows::win32::keyboard_and_mouse_input::*
        windows::win32::ldap::*
        windows::win32::legacy_windows_environment_features::*
        windows::win32::location::*
        windows::win32::machine_learning::*
        windows::win32::magnification::*
        windows::win32::mapi::*
        windows::win32::mbn::*
        windows::win32::media_foundation::*
        windows::win32::media_transport::*
        windows::win32::menus_and_resources::*
        windows::win32::mib::*
        windows::win32::mixed_reality::*
        windows::win32::mmc::*
        windows::win32::mobile_broadband::*
        windows::win32::mobile_device_management_registration::*
        windows::win32::monitor::*
        windows::win32::multicast::*
        windows::win32::multimedia::*
        windows::win32::native_wi_fi::*
        windows::win32::net_bios::*
        windows::win32::net_management::*
        windows::win32::net_shell::*
        windows::win32::network_diagnostics_framework::*
        windows::win32::network_drivers::*
        windows::win32::network_list_manager::*
        windows::win32::network_policy_server::*
        windows::win32::offline_files::*
        windows::win32::open_gl::*
        windows::win32::operation_recorder::*
        windows::win32::other_device_technologies::*
        windows::win32::p2p::*
        windows::win32::packaging::*
        windows::win32::parental_controls::*
        windows::win32::password_management::*
        windows::win32::perf::*
        windows::win32::performance_log_and_alerts::*
        windows::win32::photo_acquire::*
        windows::win32::pointer_input::*
        windows::win32::policy::*
        windows::win32::power::*
        windows::win32::print_docs::*
        windows::win32::process_snapshotting::*
        windows::win32::process_status::*
        windows::win32::projected_file_system::*
        windows::win32::quality_of_service::*
        windows::win32::radial_input::*
        windows::win32::recovery::*
        windows::win32::remote_assistance::*
        windows::win32::remote_desktop_services::*
        windows::win32::remote_differential_compression::*
        windows::win32::restart_manager::*
        windows::win32::rights_management::*
        windows::win32::routing_and_remote_access_service::*
        windows::win32::rpc::*
        windows::win32::search::*
        windows::win32::security::*
        windows::win32::sensors::*
        windows::win32::serial_controller::*
        windows::win32::services::*
        windows::win32::settings_management_infrastructure::*
        windows::win32::shell::*
        windows::win32::snmp::*
        windows::win32::software_device::*
        windows::win32::streaming_media::*
        windows::win32::structured_storage::*
        windows::win32::sync::*
        windows::win32::system_event_notification_service::*
        windows::win32::system_restore::*
        windows::win32::system_services::*
        windows::win32::tablet_pc::*
        windows::win32::tapi::*
        windows::win32::task_scheduler::*
        windows::win32::text_services::*
        windows::win32::tiles_badges_notifications::*
        windows::win32::title_callable_ui::*
        windows::win32::tool_help::*
        windows::win32::touch_input::*
        windows::win32::tpm_base_services::*
        windows::win32::ui_animation::*
        windows::win32::upnp::*
        windows::win32::ual::*
        windows::win32::usb_drivers::*
        windows::win32::user_access_logging::*
        windows::win32::virtual_storage::*
        windows::win32::web_dav::*
        windows::win32::web_sock::*
        windows::win32::wia::*
        windows::win32::win_inet::*
        windows::win32::winrt::*
        windows::win32::win_sock::*
        windows::win32::windows_accessibility::*
        windows::win32::windows_address_book::*
        windows::win32::windows_and_messaging::*
        windows::win32::windows_biometric_framework::*
        windows::win32::windows_clustering::*
        windows::win32::windows_color_system::*
        windows::win32::windows_connect_now::*
        windows::win32::windows_connection_manager::*
        windows::win32::windows_contacts::*
        windows::win32::windows_deployment_services::*
        windows::win32::windows_desktop_sharing::*
        windows::win32::windows_error_reporting::*
        windows::win32::windows_event_collector::*
        windows::win32::windows_event_log::*
        windows::win32::windows_filtering::*
        windows::win32::windows_firewall::*
        windows::win32::windows_imaging_component::*
        windows::win32::windows_information_protection::*
        windows::win32::windows_media_device_manager::*
        windows::win32::windows_media_format::*
        windows::win32::windows_media_library_sharing_services::*
        windows::win32::windows_media_player::*
        windows::win32::windows_network_virtualization::*
        windows::win32::windows_networking::*
        windows::win32::windows_portable_devices::*
        windows::win32::windows_programming::*
        windows::win32::windows_properties_system::*
        windows::win32::windows_remote_management::*
        windows::win32::windows_ribbon::*
        windows::win32::windows_server_backup::*
        windows::win32::windows_setup_and_migration::*
        windows::win32::windows_stations_and_desktops::*
        windows::win32::windows_subsystem_for_linux::*
        windows::win32::windows_sync::*
        windows::win32::windows_system_assessment_tool::*
        windows::win32::windows_update_agent::*
        windows::win32::windows_web_services::*
        windows::win32::wmi::*
        windows::win32::wpf_bitmap_effects::*
        windows::win32::xaudio2::*
        windows::win32::xinput::*
        windows::win32::xaml_diagnostics::*
        windows::win32::xaml_diganostics::*
        windows::win32::xblidp::*
        windows::win32::xml_http_extended_request::*
        windows::win32::xps::*
    );
}
